languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Josh Quinlan"
copyright = "© Josh Quinlan"

[params]
  dateFormat = "2 January, 2006"

  # mainSections = ["section1", "section2"]
  description = "British Audio Producer, Conductor & Baritone"

[params.author]
  name = "Josh Quinlan"
  image = "author.png"
  headline = "British Audio Producer, Conductor & Baritone"
  bio = "Bringing music to life through creative collaboration and meticulous craft."
  links = [
    { link = "https://joshquinlan.co.uk/" },
    { instagram = "https://instagram.com/JoshNQuinlan" },
    { x-twitter = "https://twitter.com/JoshNQuinlan" },
    { linkedin = "https://linkedin.com/in/joshnquinlan" },
    { github = "https://github.com/DonQuinleone" },
    { email = "mailto:josh@quinlan.cloud" },
  ]

